// ============================================================================
// exp_lut.sv  --  IFA-7 base-2 exponential mantissa ROM
// ----------------------------------------------------------------------------
// Combinational ROM:  data = round( 2^(-addr/LUT_DEPTH) * 2^PF ).
// Contents are generated by python/ifa7_config.py and inlined via
// exp_lut_init.svh so simulation and synthesis are guaranteed identical
// (no $readmemh file-path dependence).
//
// This realises the fractional part of  exp(x) = 2^(x*log2e):  the integer part
// is a shift performed in exp_unit.sv, the fractional part is this lookup.
// ============================================================================
`timescale 1ns/1ps
`default_nettype none

module exp_lut #(
    parameter int LUT_BITS = 8,
    parameter int LUT_W    = 18
) (
    input  wire [LUT_BITS-1:0] addr,
    output wire [LUT_W-1:0]    data
);
    localparam int DEPTH = (1 << LUT_BITS);

    // ROM storage. Initialised once at elaboration from the generated include.
    // Asynchronous (combinational) read -> distributed (LUT) ROM.
    (* rom_style = "distributed" *)
    logic [LUT_W-1:0] rom [0:DEPTH-1];

    initial begin
        `include "exp_lut_init.svh"
    end

    assign data = rom[addr];
endmodule

`default_nettype wire
