// ----------------------------------------------------------------
// ifa7_pkg.svh  --  AUTO-GENERATED by python/ifa7_config.py
// Do not edit by hand: regenerate with  `py gen_vectors.py`.
// Single source of truth for every IFA-7 numeric/structural param.
//
// NOTE: NO include guard -- this file is `include-d inside each
// module body to create module-scoped localparams.  A guard would
// let only the first including module see the parameters.
// ----------------------------------------------------------------
localparam int IFA7_DATA_W = 8;
localparam int IFA7_DK = 32;
localparam int IFA7_N = 64;
localparam int IFA7_BR = 16;
localparam int IFA7_BC = 16;
localparam int IFA7_NBLK = 4;
localparam int IFA7_ACC_W = 32;
localparam int IFA7_SF = 8;
localparam int IFA7_SCALE_SH = 12;
localparam int IFA7_SCALE_M = 185364;
localparam int IFA7_S_W = 32;
localparam int IFA7_PF = 16;
localparam int IFA7_G = 14;
localparam int IFA7_LOG2E_FIX = 23637;
localparam int IFA7_TF = 22;
localparam int IFA7_LUT_BITS = 8;
localparam int IFA7_LUT_DEPTH = 256;
localparam int IFA7_LUT_W = 18;
localparam int IFA7_P_W = 17;
localparam int IFA7_P_ZERO_GN = 71303168;
localparam int IFA7_M_INIT = -268435456;
localparam int IFA7_L_W = 40;
localparam int IFA7_ACCO_W = 48;
localparam int IFA7_OUT_F = 8;
localparam int IFA7_OUT_W = 24;
localparam int IFA7_CORE_DIV = 4;
localparam int IFA7_UART_DIV = 217;
